name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    # paths:
    #   - 'api/Dockerfile'
    #   - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t rishabkumar7/devops-qr-code-backend:latest
          docker build ./front-end-nextjs/ -t rishabkumar7/devops-qr-code-frontend:latest
      - name: push image to docker hub
        run: |
          docker login -u rishabkumar7 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push rishabkumar7/devops-qr-code-backend:latest
          docker push rishabkumar7/devops-qr-code-frontend:latest
        # Create a temporary directory for JAR files
      - name: Create temporary directory
        run: mkdir -p ./app

      # Download JAR files from S3
      - name: Download JAR files from S3
        run: aws s3 cp s3://cca670-tickitdb/jar ./app/jar
        # For multiple JARs, use: aws s3 cp s3://your-bucket-name/ ./app/ --recursive --include "*.jar"